### ISSUE TITLE
Use python's functools.total_ordering?

### ISSUE THREAD

**Issue by jfly** [cubing/wca-regulations-compiler#1]
See [`functools.total_ordering`](https://docs.python.org/2/library/functools.html#functools.total_ordering).

I think this would be a good candidate for [`class Rule`](https://github.com/cubing/wca-regulations-compiler/blob/894e97649ee2dafb7e454ba53e5989b75e4680ee/wrc/sema/ast.py#L78-L82), because it already has more than 1 of these ordering functions defined.

**Comment by viroulep** [comment]
Right, thanks I didn't know about that!
Plus I should have implemented `__eq__` so that it's explicitly consistent with `__hash__`.
